test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>
# amazon:
#   service: S3
#   access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
#   bucket: <%= ENV['AWS_S3_BUCKET'] %>
#   region: <%= ENV['AWS_S3_REGION'] %>
#   secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
